### ISSUE TITLE
CI/CD Pipeline Setup

### ISSUE THREAD

**Issue by ishanppendse** [Team-07-CSE-210-FA-24/cse210-fa24-group07#3]
# Tasks
- [x] Set up initial ElectronJS app - @McSohan 
- [x] Set up basic GitHub CI/CD - @ishanppendse 
- [x] Linting and Formatting - @amnore 
- [x] Testing - Zhihang Li
- [x] Set up Code Quality Tool (SonarQube) - @bdasgupta027 
- [x] Document Generation - @bdasgupta027 
- [x] Create submission document
- [ ] Deployment pipeline
- [ ] End-To-End testing
- [x] Bug fix, enable CI/CD pipeline to run - @bdasgupta027 

The [`CI_CD_Pipeline`](https://github.com/ishanppendse/cse210-fa24-group07/tree/CI_CD_Pipeline) branch is used to test out the CI/CD pipeline as we work on this issue.

# Bottlenecks
None

**Comment by McSohan** [comment]
Can someone check MacOS part of the build in the pipeline? Its building and zipping - but not sure if its running.

**Comment by ishanppendse** [comment]
End to End testing not implemented due to time constraint. Deployment pipeline not applicable.
